In [2]:
import numpy as np

In [3]:
v=np.arange(0,6,1) #范围0，5闭区间，间隔为1的一维数组
print(v)
print(v.shape)

print('——'*20)
print(f'重塑为(2,3),mata=')
#置换和重塑不改变元素及其总个数，只变其索引（置换），变索引即形状（重塑）
mata=v.reshape(2,3)
print(mata) 
print(mata.shape)
print(f'索引[1,1]的元素为{mata[1,1]}')
#如果不把v.reshape装进mat，不会更改原来的v,直接print v仍会打印[0 1 2 3 4 5 ]
print(f'重塑为(3,2),matb=')
matb=v.reshape(3,2)
print(matb)
print(matb.shape)
print(f'索引[2,0]的元素为{matb[2,0]}')

print('——'*20) 
print(f'置换，在二维等价于矩阵转置')
matat=mata.transpose()        #不要忘了打这个()，即使它是空的
print(f'mata转置=')
print(matat)
print(f'!（至少在python里）不等于把mata重塑为(3,2)！')
print(mata.reshape(3,2))
print(f'但mata重塑为(3,2)=matb，说明从同一个原始数组无论怎么or多少次reshape，只要最终形状一样就一样')

[0 1 2 3 4 5]
(6,)
————————————————————————————————————————
重塑为(2,3),mata=
[[0 1 2]
 [3 4 5]]
(2, 3)
索引[1,1]的元素为4
重塑为(3,2),matb=
[[0 1]
 [2 3]
 [4 5]]
(3, 2)
索引[2,0]的元素为4
————————————————————————————————————————
置换，在二维等价于矩阵转置
mata转置=
[[0 3]
 [1 4]
 [2 5]]
!（至少在python里）不等于把mata重塑为(3,2)！
[[0 1]
 [2 3]
 [4 5]]
但mata重塑为(3,2)=matb，说明从同一个原始数组无论怎么or多少次reshape，只要最终形状一样就一样


In [4]:
print(f'高维数组')
a=np.arange(0,24,1)
tena=a.reshape(2,3,4)
print(f'形状{tena.shape}的tena=')
print(tena)

print('——'*20)
print(f'索引[0,2,1]的元素为{tena[0,2,1]}')
print(f'索引[1,1,3]的元素为{tena[1,1,3]}')

print('——'*20)
print(f'python高维数组形状/索引规律：都是【从左到右,最外->最内】。（不要试图想象>3维的东西，只需记住此规律直接编程！')
print(f'形状(圆括号)：(最外层层数, ... ,最内层元素数)  三维:(层数,行数,列数)')
print(f'索引[方括号,不要忘了-1]：[最外层索引, ... ,最内层索引]    三维:[层标,行标,列标]')

print('——'*20)
print(f'高维数组置换')
tenaT1=tena.transpose(0,2,1)   # 将轴顺序从 (0,1,2) 变为 (0,2,1)  ,注意这是轴，即索引的索引！
print(f'形状{tenaT1.shape}的tenaT1=')
print(tenaT1)
tenaT2=tena.transpose(2,1,0)   # 将轴顺序从 (0,1,2) 变为 (2,1,0)
print(f'形状{tenaT2.shape}的tenaT2=')
print(tenaT2)



高维数组
形状(2, 3, 4)的tena=
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
————————————————————————————————————————
索引[0,2,1]的元素为9
索引[1,1,3]的元素为19
————————————————————————————————————————
python高维数组形状/索引规律：都是【从左到右,最外->最内】。（不要试图想象>3维的东西，只需记住此规律直接编程！
形状(圆括号)：(最外层层数, ... ,最内层元素数)  三维:(层数,行数,列数)
索引[方括号,不要忘了-1]：[最外层索引, ... ,最内层索引]    三维:[层标,行标,列标]
————————————————————————————————————————
高维数组置换
形状(2, 4, 3)的tenaT1=
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]
形状(4, 3, 2)的tenaT2=
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [5]:
print('——'*20)
print(f'生成一个4阶张量,以前从来没干过')
q=np.arange(0,120)
quadten=q.reshape(2,3,4,5)
print(quadten)
print(f'索引为[1,0,1,1]的元素为{quadten[1,0,1,1]}')
print(f'索引为[1,1,1,3]的元素为{quadten[1,1,1,3]}')
print(f'这验证了之前的索引规则')

————————————————————————————————————————
生成一个4阶张量,以前从来没干过
[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]
索引为[1,0,1,1]的元素为66
索引为[1,1,1,3]的元素为88
这验证了之前的索引规则


In [ ]:
#np.random.seed(0)  #设置随机数生成器的种子为 0。这样每次运行代码时生成的随机数都是相同的，便于结果可复现。
dim=3
#x=np.random.randn(dim,)    #deepseek: 这个逗号不是必须的
#y=np.random.randn(dim)
x=np.arange(0,3);y=np.arange(3,6)
# x.shape：数组的形状，例如 (3,)。

# x.dtype：数组中元素的数据类型，例如 float64。

# x.ndim：数组的维度数（轴的数量），这里是 1。

# x.size：数组元素的总个数，这里是 3

print(f'{type(x)} 形状{x.shape}x={x}')
print(f'{type(y)} 形状{y.shape}y={y}')

print('——'*20)
print(f'以下三种写法给出一样的点乘x.y=')
print(f'它们都不自带复共轭,故我没写<bra|ket>')
print(np.inner(x,y))
print(np.dot(x,y))             #根据输出,编程顺序与数学顺序一致         
print(x.dot(y))

print('——'*20)
print(f'外积|x><y|生成一个{dim}*{dim}的矩阵u=：')
u=np.outer(x,y)
print(u)
print(f'外积v=|y><x|一般与其不相等')     #根据输出,编程顺序与数学顺序一致
v=np.outer(y,x)
print(v)

print('——'*20)
print(f'张量积(又称为kronecker积)|x>⊗|y>给出的是在自然正交归一基|ex_i>⊗|ey_j>下的分量，仍为一维数组，只不过长度为{dim}*{dim}={dim*dim}')
xty=np.kron(x,y)
ytx=np.kron(y,x)
print(f'|x>⊗|y>=')
print(xty)
print(f'显然地，二者不相等，|y>⊗|x>=')
print(ytx)

<class 'numpy.ndarray'> 形状(3,)x=[0 1 2]
<class 'numpy.ndarray'> 形状(3,)y=[3 4 5]
————————————————————————————————————————
以下三种写法给出一样的点乘x.y=
它们都不自带复共轭,故我没写<bra|ket>
14
14
14
————————————————————————————————————————
外积|x><y|生成一个3*3的矩阵u=：
[[ 0  0  0]
 [ 3  4  5]
 [ 6  8 10]]
外积v=|y><x|一般与其不相等
[[ 0  3  6]
 [ 0  4  8]
 [ 0  5 10]]
————————————————————————————————————————
张量积(又称为kronecker积)|x>⊗|y>给出的是在自然正交归一基|ex_i>⊗|ey_j>下的分量，仍为一维数组，只不过长度为3*3=9
|x>⊗|y>=
[ 0  0  0  3  4  5  6  8 10]
显然地，二者不相等，|y>⊗|x>=
[ 0  3  6  0  4  8  0  5 10]


In [7]:
print(f'以下表格由deepseek给出')
"""
| 物理操作（手写）      | NumPy 等价代码                         | 注意事项                                |
|-------------------- |-------------------------------------  |-----------------------------------------|
| |x⟩ ⊗ |y⟩           |   np.kron(x, y)                       | 一维数组视为列向量，顺序：x 为主序         |
| |x⟩⟨y|               |   np.outer(x, y.conj())               | 必须对第二个向量取复共轭                  |
| ⟨x|y⟩                |   np.vdot(x, y) 或 x.conj() @ y       | 共轭线性于第一个参数，符合物理约定         |
| 矩阵乘法 AB          |   A @ B                               | 标准矩阵乘法，不自动取共轭转置             |
| 矩阵的 Hermitian 共轭 |  A.conj().T 或 A.H (NumPy 1.14+)     | 等价于 A^†                               |
"""

以下表格由deepseek给出


'\n| 物理操作（手写）      | NumPy 等价代码                         | 注意事项                                |\n|-------------------- |-------------------------------------  |-----------------------------------------|\n| |x⟩ ⊗ |y⟩           |   np.kron(x, y)                       | 一维数组视为列向量，顺序：x 为主序         |\n| |x⟩⟨y|               |   np.outer(x, y.conj())               | 必须对第二个向量取复共轭                  |\n| ⟨x|y⟩                |   np.vdot(x, y) 或 x.conj() @ y       | 共轭线性于第一个参数，符合物理约定         |\n| 矩阵乘法 AB          |   A @ B                               | 标准矩阵乘法，不自动取共轭转置             |\n| 矩阵的 Hermitian 共轭 |  A.conj().T 或 A.H (NumPy 1.14+)     | 等价于 A^†                               |\n'

In [8]:
print(f'张量单重缩并tensordot')
tA=np.random.randn(5,3,2)    #两个高阶张量
tB=np.random.randn(3,6,4)
print(f'tA形状:{tA.shape},tB形状:{tB.shape}')

tC=np.tensordot(tA,tB,[[1],[0]])   #这代表缩并tA的第2个指标和tB的第1个指标，注意[[]，[]]
print(f'tC形状:{tC.shape}')


张量单重缩并tensordot
tA形状:(5, 3, 2),tB形状:(3, 6, 4)
tC形状:(5, 2, 6, 4)


$$
\sum_{abc} A_{iba} B_{jcb} C_{kac}
$$

In [9]:
print(f'张量多重缩并einsum')
A=np.random.randn(5,3,3)
B=np.random.randn(6,3,3)
C=np.random.randn(4,3,3)
#T=np.tensordot(A,B,C,[[1],[0]])，多重缩并不能用tensordot了，用einstein求和func
#但网课里写的是 iab,jbc,kca
T=np.einsum('iba,jcb,kac->ijk',A,B,C)        #einstein求和固定格式，注意对应！！
print(f'T形状:{T.shape}')

#也可以写成iab,jca,kbc,因为缩并是哑标，可以随便重命名，缩并对应槽位正确即可
#都是 A_2和B_3, A_3和C_2, B_2和C_3 数字代表槽位的缩并
Tnew=np.einsum('iab,jca,kbc->ijk',A,B,C)
print(f'验证 T 和 Tnew 是否相等：{np.allclose(T, Tnew)}')

print('——'*20)
#但网课里写的是 iab,jbc,kca
Twk=np.einsum('iab,jbc,kca->ijk',A,B,C)
print(f'验证 T 和 Twk 是否相等：{np.allclose(T, Twk)}')

#个人认为这来自张量网络图中‘腿’和指标的顺序对应约定问题

张量多重缩并einsum
T形状:(5, 6, 4)
验证 T 和 Tnew 是否相等：True
————————————————————————————————————————
验证 T 和 Twk 是否相等：False


In [10]:
"""
np.allclose 功能：比较两个数组是否在容差范围内近似相等（逐元素比较！）。
语法：np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
参数：
  a, b : 输入数组
  rtol : 相对容差
  atol : 绝对容差
  equal_nan : 是否将 NaN 视为相等
返回：布尔值，True 表示所有元素满足 |a - b| <= atol + rtol * |b|。可认为a,b两个数组相等

为什么比手写 for 循环快？
- 使用 NumPy 向量化操作，底层 C 语言实现，避免 Python 解释器循环开销。
- 对于高维大数组性能提升显著，可达几个数量级。

与 np.array_equal 区别：
- np.array_equal 检查精确相等（元素完全相同），适合整数或布尔数组。
- np.allclose 允许微小误差，适合浮点数比较。

示例：
import numpy as np
a = np.random.randn(5,6,4)
b = a + 1e-7
print(np.allclose(a, b))      # 默认容差下很可能返回 True
print(np.allclose(a, b, rtol=1e-10))  # 更严格容差可能返回 False
"""

'\nnp.allclose 功能：比较两个数组是否在容差范围内近似相等（逐元素比较！）。\n语法：np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)\n参数：\n  a, b : 输入数组\n  rtol : 相对容差\n  atol : 绝对容差\n  equal_nan : 是否将 NaN 视为相等\n返回：布尔值，True 表示所有元素满足 |a - b| <= atol + rtol * |b|。可认为a,b两个数组相等\n\n为什么比手写 for 循环快？\n- 使用 NumPy 向量化操作，底层 C 语言实现，避免 Python 解释器循环开销。\n- 对于高维大数组性能提升显著，可达几个数量级。\n\n与 np.array_equal 区别：\n- np.array_equal 检查精确相等（元素完全相同），适合整数或布尔数组。\n- np.allclose 允许微小误差，适合浮点数比较。\n\n示例：\nimport numpy as np\na = np.random.randn(5,6,4)\nb = a + 1e-7\nprint(np.allclose(a, b))      # 默认容差下很可能返回 True\nprint(np.allclose(a, b, rtol=1e-10))  # 更严格容差可能返回 False\n'

In [ ]:
#张量积和einsum
print(f' 形状{x.shape}x={x}')
print(f' 形状{y.shape}y={y}')
w=np.einsum('i,j->ij',x,y)
print(f' 形状{w.shape}w=')
print(f' {w}')
#这实际等价于前面的“外积”np.outer(x,y)
wkron=w.reshape(9,)
print(f' 形状{wkron.shape}wkronw=')
print(f' {wkron}')
#这才和xty=np.kron(x,y)一样

 形状(3,)x=[0 1 2]
 形状(3,)y=[3 4 5]
 形状(3, 3)w=
 [[ 0  0  0]
 [ 3  4  5]
 [ 6  8 10]]
 形状(9,)wkronw=
 [ 0  0  0  3  4  5  6  8 10]
